name: Test Postman Publish

on:
  workflow_dispatch:

jobs:
  test-postman-actions:
    runs-on: ubuntu-latest
    env:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      SOURCE_COLLECTION_ID: ${{ vars.SOURCE_COLLECTION_ID }}
      DESTINATION_COLLECTION_ID: ${{ vars.DESTINATION_COLLECTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Test Publish Collection
        uses: ./actions/publish-changes
        with:
          postman_api_key: ${{ secrets.POSTMAN_API_KEY }}
          source_collection_id: ${{ vars.SOURCE_COLLECTION_ID }}
          destination_collection_id: ${{ vars.DESTINATION_COLLECTION_ID }}
